import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  overviewSidebar: [
    {
      type: 'autogenerated',
      dirName: 'overview',
    },
  ],
  architectureSidebar: [
    {
      type: 'autogenerated',
      dirName: 'architecture',
    },
  ],
  specsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'specs',
    },
  ],
  changelogSidebar: [
    {
      type: 'autogenerated',
      dirName: 'changelog',
    },
  ],
  inboxSidebar: [
    {
      type: 'autogenerated',
      dirName: 'inbox',
    },
  ],
};

export default sidebars;
