import type { ReactNode } from "react";
import useBaseUrl from "@docusaurus/useBaseUrl";
import categoryNav from "@site/src/data/category-nav.json";
import styles from "./styles.module.css";

type CategoryKey = keyof typeof categoryNav;

interface Page {
  docId: string;
  title: string;
  position: number;
}

interface Subcategory {
  key: string;
  title: string;
  docId: string;
  position: number;
  pages: Page[];
}

interface CategoryData {
  pages: Page[];
  subcategories: Subcategory[];
}

interface CategoryNavProps {
  category: CategoryKey;
}

/**
 * Auto-generated navigation list for category index pages
 * Uses data from category-nav.json (generated by scripts/generate-category-nav.js)
 * Supports nested subcategories with ul > li > ul > li structure
 */
export default function CategoryNav({ category }: CategoryNavProps): ReactNode {
  // Get the base URL for docs
  const docsBaseUrl = useBaseUrl("/");

  const data = categoryNav[category] as CategoryData;

  if (!data) {
    return <p className={styles.empty}>Category not found.</p>;
  }

  const { pages, subcategories } = data;
  const hasContent = pages.length > 0 || subcategories.length > 0;

  if (!hasContent) {
    return <p className={styles.empty}>No pages in this category yet.</p>;
  }

  return (
    <ul className={styles.navList}>
      {pages.map((page) => (
        <li key={page.docId} className={styles.navItem}>
          <a href={`${docsBaseUrl}${page.docId}`}>{page.title}</a>
        </li>
      ))}
      {subcategories.map((subcat) => (
        <li key={subcat.key} className={styles.navItem}>
          <a href={`${docsBaseUrl}${subcat.docId}`}>{subcat.title}</a>
          {subcat.pages.length > 0 && (
            <ul className={styles.navList}>
              {subcat.pages.map((page) => (
                <li key={page.docId} className={styles.navItem}>
                  <a href={`${docsBaseUrl}${page.docId}`}>{page.title}</a>
                </li>
              ))}
            </ul>
          )}
        </li>
      ))}
    </ul>
  );
}
